name: React Build
on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@master
        
      - name: 의존성 파일 설치
        run: npm install

      - name: React 빌드
        run: npm run build
