name: React Build
on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: node_modules 디렉토리캐싱
        uses: actions/cache@v1
        with: 
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
        
      - name: 의존성 파일 설치
        run: yarn install

      - name: React 빌드
        run: yarn build

      - name: 빌드된 파일에 appspec.yml 복사
        run: cp appspec.yml ./build

      - name: 빌드된 파일 압축파일 생성
        run: tar cvf build.tar build

      - name: 빌드파일 s3에 업로드
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy push \
            --region ap-northeast-2 \
            --application-name carrot-farm-deploy \
            --description "carrot farm test build" \
            --s3-location s3://carrot-farm-deploy-bucket/buildTest.zip \
            --source ./build \
            --ignore-hidden-files

      - name: s3에 업로드된 파일 배포
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
            --region ap-northeast-2 \
            --application-name carrot-farm-deploy \
            --deployment-group-name carrot-farm-deploy-group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --s3-location bucket=carrot-farm-deploy-bucket,bundleType=zip,key=buildTes 
t.zip
        
        





