name: React Build
on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: 레포지토리 체크아웃
        uses: actions/checkout@master

      - name: node_modules 디렉토리캐싱
        uses: actions/cache@v1
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      - name: 의존성 파일 설치
        run: yarn install

      - name: React 빌드
        run: yarn build

